### ISSUE TITLE
MSRV stats

### ISSUE THREAD

**Issue by james7132** [szabgab/rust-digger#53]
I'm curious about the MSRV distribution of published crates. This should be readable via the `rust-version` field in Cargo.toml, which was added in Rust 1.56. Anything that doesn't specify it, or specifies it in the README will likely have an older MSRV.

**Comment by szabgab** [comment]
Before I get started on this I wanted to understand what MSRV stands for as I don't recall seeing that acronym earlier.

MSRV = Minimum Supported Rust Version

A few links about the topic:
* [Crate Edition / MSRV](https://users.rust-lang.org/t/crate-edition-msrv/97744)
* [What's your crate's Minimum Supported Rust Version? ](https://dev.to/pnehrer/whats-your-crates-minimum-supported-rust-version-28mh)
* [The cargo-msrv Book](https://gribnau.dev/cargo-msrv/index.html)

[The manifest format](https://doc.rust-lang.org/cargo/reference/manifest.html) describes two fields the `package/edition` and the `package/rust-version`. Both are optional.

We would want to create stats on the number of crates per rust-version (and the number of crates that don't have it at all)
Same with edition. (we would also want to see the list of those crates)

We would probably want to see the list of crates that have both fields and the list of crates that have neither of them.

**Comment by szabgab** [comment]
See the collected data: https://rust-digger.code-maven.com/msrv

Take in account that this information is collected from repositories and for 20% of the crates we don't even know the repository.

**Comment by szabgab** [comment]
Also currently we only check `Cargo.toml` in the root of the repositories. Repositories that hold a number of crates might not have that information in the main `Cargo.toml`.

**Comment by james7132** [comment]
The stats look wrong to me. You may need to account for those writing it as `rust-version` instead of `rust_version`.

**Comment by szabgab** [comment]
OK, now the code looks at the `rust-version` field as well. It looks way more interesting.

**Comment by szabgab** [comment]
Finally I changed the code to look at the Cargo.toml files in the crates downloaded from Crates.io
Also managed to fix the listings so now you can actually find the list of the (most recent 100) crates for each version number and each edition.
