### ISSUE TITLE
Recommend setting  GIT_TERMINAL_PROMPT to 0

### ISSUE THREAD

**Issue by richardscollin** [szabgab/rust-digger#62]
I'm modifying your code quite a bit to improve cloning speed. I noticed the following problem in my own code and thought you might have the same issue.

Doing a git clone by spawning the command will trigger some repos to hang because they are waiting for user input at the command line. It's likely these repos exist and are private on github. You can disable this with the GIT_TERMINAL_PROMPT environment variable like so.

```
std::env::set_var("GIT_TERMINAL_PROMPT", "0");
```

**Comment by szabgab** [comment]
Interesting. I think I had some code that was checking if the git repo is accessible before trying to clone, exactly to avoid this problem. I'll look into this. Thanks.

**Comment by szabgab** [comment]
done. thanks.
